# 该 workflow 将安装 Python 依赖，运行代码，并提交更新到 GitHub

name: 3958

on:
  #schedule:
    # 设置为 UTC 时间，UTC23点对应北京时间7点
    #- cron: '00 23 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'  # 启用 pip 缓存，加速安装

    - name: 安装依赖
      run: pip install -r requirements.txt

    - name: 运行 Python 代码
      run: python py/3958.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ydyp: ${{ secrets.ydyp }}

    - name: commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add 3958.log
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
    - name: push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
          github_token: ${{ secrets.TOKEN }}
          branch: main 

