# 该 workflow 将安装 Python 依赖，运行代码，并提交更新到 GitHub

name: 5968

on:
  #schedule:
    # 设置为 UTC 时间，UTC23点对应北京时间7点
    #- cron: '00 23 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'  # 启用 pip 缓存，加速安装

    - name: 安装依赖
      run: pip install -r requirements.txt

    - name: 运行 Python 代码
      run: python py/5968.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ydyp: ${{ secrets.ydyp }}

    - name: Append app.log content to Gist
      env:
        GH_TOKEN: ${{ secrets.GIST_TOKEN }}
      shell: pwsh
      run: |
        # 设置 Gist ID
        $GIST_ID = "cfd5113bc8f9d4ad710ff91af1967ec4"

        # 确保 GitHub CLI 认证
        echo $env:GH_TOKEN | gh auth login --with-token
        gh auth status

        # 下载 Gist 现有内容
        $current_content = gh gist view $GIST_ID --raw 2>$null

        # 读取 app.log 内容
        $new_content = Get-Content app.log -Raw

        # 追加日志到现有内容
        $updated_content = "$current_content`n$new_content"

        # 将更新后的内容写入临时文件
        $temp_file = "updated_log.txt"
        $updated_content | Set-Content $temp_file

        # 更新 Gist
        gh gist edit $GIST_ID --add $temp_file

