# 该 workflow 将安装 Python 依赖，运行代码，并提交更新到 GitHub

name: 8701

on:
  #schedule:
    # 设置为 UTC 时间，UTC23点对应北京时间7点
    #- cron: '00 23 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'  # 启用 pip 缓存，加速安装

    - name: 安装依赖
      run: pip install -r requirements.txt

    - name: 运行 Python 代码
      run: python py/8701.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        ydyp: ${{ secrets.ydyp }}

    - name: 追加日志到 Gist
      uses: actions/github-script@v7
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      with:
        github-token: ${{ secrets.GIST_TOKEN }}
        script: |
          const fs = require('fs');

          // 获取当前 Gist 内容
          const gistResponse = await github.request("GET /gists/${process.env.GIST_ID}", {
            headers: { authorization: `token ${process.env.GIST_TOKEN}` }
          });

          let oldContent = gistResponse.data.files["8701.log"]?.content || "";
          let newContent = fs.readFileSync('8701.log', 'utf8');

          // 追加新日志
          let updatedContent = oldContent + "\n" + newContent;

          // 更新 Gist
          await github.request("PATCH /gists/${process.env.GIST_ID}", {
            headers: {
              authorization: `token ${process.env.GIST_TOKEN}`
            },
            files: {
              "2888.log": {
                content: updatedContent
              }
            }
          });

          console.log("Gist 追加更新成功: https://gist.github.com/${process.env.GIST_ID}");




